version: '2'

services:

  db46131564:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: password

  app:
    image: veera0921/46131564
    build:
      context: .
    restart: always
    environment:
      DBHOST: db56131564
      DBPORT: 5432
      DBNAME: postgres
      DBUSERNAME: postgres
      DBPASSWORD: password
    ports:
      - 30251:8093
    depends_on:
      - db46131564
